# Generated by Django 4.2.3 on 2023-08-13 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service_request",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 8, 13, 12, 10, 14, 446104),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 8, 13, 12, 10, 14, 446104),
                null=True,
            ),
        ),
    ]
